# Generated by Django 5.2 on 2025-04-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_active_users_is_admin_users_is_staff_and_more'), ]

    operations = [
        migrations.DeleteModel(
            name='Administrateur',
        ),
    ]
