# Generated by Django 5.2 on 2025-04-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_station_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='power',
        ),
    ]
