# Generated by Django 5.2 on 2025-04-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_remove_station_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='puissance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
