# Generated by Django 5.1.7 on 2025-04-29 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_alter_station_puissance'),
        ('users', '0003_delete_administrateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ID_Reservation',
                 models.AutoField(
                     primary_key=True,
                     serialize=False)),
                ('time_start',
                 models.DateTimeField()),
                ('duration',
                 models.FloatField()),
                ('time_end',
                 models.DateTimeField()),
                ('power',
                 models.FloatField(
                     blank=True,
                     null=True)),
                ('price',
                 models.FloatField(
                     blank=True,
                     null=True)),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('ID_Station',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='reservations',
                     to='stations.station')),
                ('username',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='users.proprietaireve')),
            ],
        ),
    ]
